### ISSUE TITLE
Failed to load the autocomplete-robot-framework package

### ISSUE THREAD

**Issue by jagadeesanj** [gliviu/autocomplete-robot-framework#4]
[Enter steps to reproduce:]

1. I could not do apm install autocomplete-robot-framework as my proxy server won't allow.
   So I unpacked the contents to the .atom/packages folder
2. started the Atom editor

**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [autocomplete-robot-framework](https://github.com/gliviu/autocomplete-robot-framework) package 3.3.0

### Stack Trace

Failed to load the autocomplete-robot-framework package

```
At Cannot find module 'minimatch'

Error: Cannot find module 'minimatch'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.23.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-robot-framework-3.3.0/lib/autocomplete-plus-provider.js:5:19)
    at /packages/autocomplete-robot-framework-3.3.0/lib/autocomplete-plus-provider.js:463:26)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.23.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-robot-framework-3.3.0/lib/main.js:7:33)
    at /packages/autocomplete-robot-framework-3.3.0/lib/main.js:87:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.23.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.23.0/resources/app/src/package.js:937:35)
    at ~/AppData/Local/atom/app-1.23.0/resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.23.0/resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.23.0/resources/app/src/package-manager.js:618:16)
    at config.transact (~/AppData/Local/atom/app-1.23.0/resources/app/src/package-manager.js:531:20)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-robot-framework 3.3.0 
language-robot-framework 2.2.0 
```

**Comment by gliviu** [comment]
This is not a problem with atom or this package.
Your best option would be to properly configure the proxy. I found some [instructions](https://discuss.atom.io/t/is-there-any-proxy-settings/710/31).

If that is not possible you'll need some preinstalled packages.
[arf.zip](https://drive.google.com/file/d/1u3WSVLkSUTyMY5lfAHuDeDCkSoy-6onn/view?usp=sharing)
Unpack it and
```
cd language-robot-framework/
apm link
cd ..
cd autocomplete-robot-framework/
apm link
```
Be sure to remove first what you manually added in .atom/packages folder.

**Comment by jagadeesanj** [comment]
Thanks for the quick reply. 
Would it be possible to put the arf.zip file somewhere in the location under http://atom.io ?
I am unable to get to the arf.zip that points to https://drive.google.com/file/d/1u3WSVLkSUTyMY5lfAHuDeDCkSoy-6onn/view?usp=sharing
Thanks.
cheers,
jay

**Comment by gliviu** [comment]
Strange you were unable to download from that public link. I uploaded it on file.io. After you download the file will be deleted so you won't have another chance :)
https://file.io/hvHQ7O

**Comment by jagadeesanj** [comment]
Thanks for the new url.
Although I am able to download your zip file on my host laptop, I am still unable to copy it to my VDI machine, which is where I do the development using Atom Editor. 
Tried to use the file.io link on my VDI machine, but the proxy refuses.
But that is ok, I will ask our admin to copy it to our fileserver accessible from VDI.
Thank you once again for all the help. Very much appreciated. :)
cheers,
jay

**Comment by VernonCrabtree** [comment]
Great that gliviu was helped out with a once-off download.
I have the same error after doing an offline install with adm and also cannot download the link. 
I cannot get the proxy settings to work with Atom.
Can the arf.zip be made available please?

**Comment by gliviu** [comment]
I uploaded all files into a new location - [arf-offline](https://drive.google.com/drive/folders/1C7nlZphsGe-ZpbtSshzKckCuGHZUMhQw).
You should unzip all archives into `~/.atom/packages`.
Let me know if it doesn't work.
