### ISSUE TITLE
Autocomplete with remote libraries tries to connect localhost only

### ISSUE THREAD

**Issue by sampeson** [gliviu/autocomplete-robot-framework#5]
I have in test data this kind of remote library import:
```
Library    Remote    http://192.168.x.y:8270    WITH NAME    MySpecialLibrary
```

It fails in `Reload autocomplete data` like this:
```
File: MySpecial_test.robot
    Status: Parsed/Ok
    Path: C:\repos\MySpecialLibrary\src\acceptance_tests\MySpecial_test.robot
    Libraries
        BuiltIn
            Status: Loaded
            Source: C:\Python27\lib\site-packages\robot\libraries\BuiltIn.py
            Libdoc: C:\Users\MY~1\AppData\Local\Temp\robot-lib-cache\BuiltIn.xml
        Remote
            Status: Errors occurred during loading
            Error:
                Unexpected error: Getting keyword names from library 'Remote' failed: Calling dynamic method 'get_keyword_names' failed: Connecting remote server at http://127.0.0.1:8270 failed: [Errno 10061] No connection could be made because the target machine actively refused it, Traceback (most recent call last):
                File "C:\Users\my_name\.atom\packages\autocomplete-robot-framework\lib\library_cache.py", line 154, in _store_libraries
                xml_libdoc_path = _generate_libdoc_xml(library_name, cache_dir)
                File "C:\Users\my_name\.atom\packages\autocomplete-robot-framework\lib\library_cache.py", line 125, in _generate_libdoc_xml
                libdoc = LibraryDocumentation(library_or_resource=library_name)
                File "C:\Python27\lib\site-packages\robot\libdocpkg\__init__.py", line 35, in LibraryDocumentation
                libdoc = builder.build(library_or_resource)
                File "C:\Python27\lib\site-packages\robot\libdocpkg\robotbuilder.py", line 32, in build
                lib = TestLibrary(name, args)
                File "C:\Python27\lib\site-packages\robot\running\testlibraries.py", line 54, in TestLibrary
                lib.create_handlers()
                File "C:\Python27\lib\site-packages\robot\running\testlibraries.py", line 100, in create_handlers
                self._create_handlers(self.get_instance())
                File "C:\Python27\lib\site-packages\robot\running\testlibraries.py", line 222, in _create_handlers
                % (self.name, message), details)
                DataError: Getting keyword names from library 'Remote' failed: Calling dynamic method 'get_keyword_names' failed: Connecting remote server at http://127.0.0.1:8270 failed: [Errno 10061] No connection could be made because the target machine actively refused it
            Source: n/a
            Libdoc: n/a
    Resources
        No resources imported
```

If I create xml from library locally and change library import to `Library   MySpecialLibrary` it works OK.

Versions:
autocomplete-robot-framework 3.4.0
atom 1.25.0 x64
robotframework 3.0.2
Python 2.7.13
Windows 10

**Comment by gliviu** [comment]
Thanks for reporting. I'll take a look.

**Comment by gliviu** [comment]
The error is quite clear from stack trace:
> at http://127.0.0.1:8270 failed: [Errno 10061] No connection could be made because the target machine actively refused it,

However even if you make it work, it will not suggest any keywords from that library.
Neither remote libraries are currently supported, nor 'WITH NAME' modifier.
