### ISSUE TITLE
Failed to activate the autocomplete-robot-framework package

### ISSUE THREAD

**Issue by MrBIN89** [gliviu/autocomplete-robot-framework#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 ia32
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-robot-framework](https://github.com/gliviu/autocomplete-robot-framework) package 3.6.0

### Stack Trace

Failed to activate the autocomplete-robot-framework package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:1210129)
    at CompositeDisposable.add (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:1211097)
    at Object.consumeProvider (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:162220)
    at Object.consumeProvider_2 (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:161918)
    at Provider.t.exports.Provider.provide (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1116477)
    at ServiceHub.t.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3534008)
    at Package.activateServices (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3542194)
    at Package.activateNow (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3539249)
    at measure (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3538573)
    at Package.measure (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3536204)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3538433)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3538376)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:381112)
    at ~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:934678
    at r (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:929284)
    at n (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1119384)
    at e.bufferStream (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1119472)
    at Socket.e.on (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1118140)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -7:15.9.0 editor:select-to-first-character-of-line (input.hidden-input)
     -6:50.8.0 core:backspace (input.hidden-input)
     -6:46 editor:select-to-first-character-of-line (input.hidden-input)
     -6:26.7.0 Robot Framework:Show autocomplete status (input.hidden-input)
     -3:39.2.0 Robot Framework:Print autocomplete debug info (pre.native-key-bindings)
     -3:31.3.0 script:run-by-line-number (pre.native-key-bindings)
     -2:27.6.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -2:24.6.0 script:run-by-line-number (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
 18x -2:19.4.0 intentions:highlight (input.hidden-input)
  2x -2:09.4.0 editor:select-to-first-character-of-line (input.hidden-input)
  3x -1:59.3.0 core:backspace (input.hidden-input)
     -1:57.2.0 core:delete (input.hidden-input)
     -1:56.9.0 intentions:highlight (input.hidden-input)
     -1:56.8.0 core:save (input.hidden-input)
     -1:54.9.0 intentions:highlight (input.hidden-input)
     -1:54.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.14.1 
autocomplete-robot-framework 3.6.0 
busy-signal 2.0.1 
git-diff-details 1.4.0 
highlight-selected 0.16.0 
hyperclick 0.1.5 
hyperclick-robot-framework 1.9.0 
intentions 1.1.5 
language-robot-framework 2.4.0 
linter 2.3.0 
linter-python-pep8 0.2.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
pretty-json 2.1.2 
python-autopep8 0.1.3 
python-tools 0.6.9 
script 3.18.1 
split-diff 1.6.0 
```

**Comment by gliviu** [comment]
Still happens? Works fine for me on same atom version.
